site_name: CNUH_Rheumatology

theme:
  name: material
  language: kr
  font:
    text: Lato
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.footer

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: 
        - en
        - ko

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: 'index.md'
  - Docs: 
     - "Introduction" : 
        - "Introduction" : 'intro/Rheumatology_Introduction.md'
        - "Approach" : 'intro/approach.md'
        - "Criteria" : 'intro/criteria.md'
        - "div" : 'intro/div.md'
     - "Dx. Tests & Meds" : 'approach.md'
     - "Rheumatoid Arthritis" : 'ra/Rheumatoid Arthritis.md'
     - "SLE" : 'sle/sle.md'
     - "APS" : 'APS/Antiphospholipid Syndrome.md'    
     - "Sjögren's syndrome" : 'sjogren/Sjogren Disease.md'
     - "Systemic Sclerosis" : 'SSc/Systemic Sclerosis.md'
     - "Idiopathic Inflammatory Myositis" : 'myopathy/IIM.md'
     - "Spondyloarthropathy" : 'spondyloarthropathy/spa_intro.md'
     - "Vasculitis" : 'vasculitis/vasculitis.md'
     - "Crystalopathy" : 'crystalopathy/gout.md'
     - "Osteoporosis" : 'osteoporosis/osteoporosis.md'
     - "Pain" : 'pain/pain.md'
     - "Other diseases" : 'other_diseases/others.md'
     - "Miscellaneous" : 
        - "Perioperative" : 'misc/perioperative.md'
        - "Pregnancy" : 'misc/pregnancy.md'
        - "Misc" : 'misc/misc.md'
